version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: covid
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    container_name: my_postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresql_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    container_name: my_pgadmin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/root/.pgadmin